# model
model_name_or_path: ...
# data
# dataset_name: ...
refresh: false
# data_tag: 'base'
data_dir: ...
data_filename: ...
train_on_inputs: false
data_max_length: 1024
# training
# trainer
peft_type: 'lora'
lora_only: false
hf_learning_rate: 0.0005
hf_weight_decay: 0
hf_lr_scheduler_type: 'linear'
hf_warmup: 0.05
tag: 'lora-qv-r2-lomo'
output_dir: 'outputs'
save_steps: 200
save_total_limit: 1
overwrite_output_dir: true
save_strategy: "steps"
deepspeed: '.../config/ds_config_lora.json'
do_train: true
do_eval: false
evaluation_strategy: 'no'
per_device_train_batch_size: ...
per_device_eval_batch_size: ...
learning_rate: 0.0005
weight_decay: 0
num_train_epochs: 3
lr_scheduler_type: 'linear'
warmup: 0.01
clip_grad_norm: 1.0
#clip_grad_value: 1.0
#clip_loss_value: 5.0
log_level: 'info'
logging_steps: 1
seed: 42
#bf16: true
remove_unused_columns: false
load_best_model_at_end: false
metric_for_best_model: 'acc'
optim: 'sgd'
group_by_length: false
#report_to: 'wandb'
dataloader_pin_memory: false
gradient_checkpointing: true
predict_with_generate: false
lora_r: 2

#wandb config
wandb_project: ...
wandb_entity: "delius-co"