# model
model_name_or_path: ...
cache_dir: ...
# data
data_dir: ...
data_filename: 'after.jsonl'
refresh: false
train_on_inputs: false
data_max_length: 1024
# training
# trainer
tag: 'lomo'
output_dir: 'outputs'
save_steps: 100
overwrite_output_dir: true
deepspeed: '.../config/ds_config.json'
do_train: true
do_eval: false
evaluation_strategy: 'no'
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
learning_rate: 0.00003
weight_decay: 0
num_train_epochs: 10
lr_scheduler_type: 'linear'
warmup: 0.1
clip_grad_norm: 1.0
save_strategy: 'no'
save_total_limit: 0
seed: 42
#bf16: true
remove_unused_columns: false
load_best_model_at_end: false
metric_for_best_model: 'acc'
group_by_length: false
#report_to: 'wandb'
dataloader_pin_memory: false
gradient_checkpointing: true
predict_with_generate: false

#wandb config
wandb_project: "lomo"
wandb_entity: "delius-co"